---
title: "Figure 1B"
output: html_document
---

```{r, message=FALSE}
library(MetaIntegrator)
library(tidyr)
library(stringr)
library(dplyr)
library(tidyverse)
library(data.table)
library(ggpubr)
library(NatParksPalettes)

set.seed(4)
```

# path setup
```{r setup_paths}
path = "" # add path
datPath = paste0(path, "data/processed_data/")
source(paste0(path,"scripts/load_mvs_genes.R"))
source(paste0(path,"scripts/functions_step45.R"))
source(paste0(path,"scripts/subset_dataobjects.R"))
source(paste0(path,"scripts/run_pooled_aurocs.R"))
fig_path = paste0(path,"figures/")
fig1_path = paste0(fig_path, "Figure1/")
fig2_path = paste0(fig_path, "Figure2/")
```


## 9a generated in step4 processing
```{r }
dat = readRDS(file = paste0(datPath, "9a_timecat_peaksubset_individual.rds"))

arena_dat = reformat(dat, arena)
arena_dat  = fix_formattedname(arena_dat)
corona_dat = reformat(dat, corona)
corona_dat  = fix_formattedname(corona_dat)
filo_dat = reformat(dat, filo)
filo_dat  = fix_formattedname(filo_dat)
flavi_dat = reformat(dat, flavi)
flavi_dat  = fix_formattedname(flavi_dat)
ortho_dat = reformat(dat, ortho)
ortho_dat  = fix_formattedname(ortho_dat)

virus_dat_list = list(arena_dat, corona_dat, filo_dat, flavi_dat, ortho_dat)
names(virus_dat_list) = c("arena", "corona", "filo", "flavi", "ortho")
saveRDS(virus_dat_list, file = paste0(datPath, "10a_virus_datlist.rds"))
```

# prep input
```{r}
dat = readRDS(file = paste0(datPath, "9a_timecat_peaksubset_individual.rds"))
virus_dat_list = readRDS(file = paste0(datPath, "10a_virus_datlist.rds"))

## get total samples
cols = c("dataset","disease","virus","virus_family", "day","animal")
df = bind_pheno_tables(dat, cols)
nrow(df)

## get total datsets
sum(length(virus_dat_list$arena$originalData), 
    length(virus_dat_list$corona$originalData),
    length(virus_dat_list$filo$originalData),
    length(virus_dat_list$flavi$originalData),
    length(virus_dat_list$ortho$originalData))

point_n = 1000
round_n = 2
arena_dat = makePooledROCplot(virus_dat_list$arena$originalData, pos.genes = mvs.up, neg.genes = mvs.down,score.overwrite.col ="MVS_score", points = point_n, rounding = round_n)
corona_dat = makePooledROCplot(virus_dat_list$corona$originalData, pos.genes = mvs.up, neg.genes = mvs.down,score.overwrite.col ="MVS_score", points = point_n, rounding = round_n)
filo_dat = makePooledROCplot(virus_dat_list$filo$originalData, pos.genes = mvs.up, neg.genes = mvs.down,score.overwrite.col ="MVS_score", points = point_n, rounding = round_n)
flavi_dat = makePooledROCplot(virus_dat_list$flavi$originalData, pos.genes = mvs.up, neg.genes = mvs.down,score.overwrite.col ="MVS_score", points = point_n, rounding = round_n)
ortho_dat = makePooledROCplot(virus_dat_list$ortho$originalData, pos.genes = mvs.up, neg.genes = mvs.down,score.overwrite.col ="MVS_score", points = point_n, rounding = round_n)


arena_plot_dat = subset_pooled_toSummary(arena_dat, paste0("Arenaviridae,\n"))
corona_plot_dat = subset_pooled_toSummary(corona_dat, paste0("Coronaviridae,\n"))
filo_plot_dat = subset_pooled_toSummary(filo_dat, paste0("Filoviridae,\n"))
flavi_plot_dat = subset_pooled_toSummary(flavi_dat, paste0("Flaviviridae,\n"))
ortho_plot_dat = subset_pooled_toSummary(ortho_dat, paste0("Orthomyxoviridae,\n"))

## combine data
combined_viruses = list(rbind(arena_plot_dat$plotdata,
                              corona_plot_dat$plotdata,
                              filo_plot_dat$plotdata,
                              flavi_plot_dat$plotdata,
                              ortho_plot_dat$plotdata),
                        rbind(arena_plot_dat$legendTextDt,
                              corona_plot_dat$legendTextDt,
                              filo_plot_dat$legendTextDt,
                              flavi_plot_dat$legendTextDt,
                              ortho_plot_dat$legendTextDt))
names(combined_viruses) = c("plotdata", "legendTextDt")
```

##graph
```{r}
colors_auroc = c(rep(viral_family_colors[1]), rep(viral_family_colors[2]), rep(viral_family_colors[3]), rep(viral_family_colors[4]),rep(viral_family_colors[5]))
names(colors_auroc) = names(combined_viruses$legendTextDt$dataset) 

combined_plot = plot_pooledROC(combined_viruses, colors = colors_auroc, legend_title = "", plottitle = "Summary ROC curves of MVS score by Virus Family") 
combined_plot_final = combined_plot+ theme(
      legend.position = c(.64, 0.3))+ theme(text = element_text(size = 20))   + theme(plot.title = element_text(size=18))+
  theme(legend.key.width = unit(1.4, 'cm'), legend.text = element_text(size=18.5))+ guides(color = guide_legend(override.aes = list(size = 3))) + guides(color = guide_legend(override.aes = list(linewidth = 3)))
combined_plot_final
ggsave(combined_plot_final, filename = paste0(fig1_path, "Fig_1C_combined_auc_plots.png"), height = 7, width = 7)
```



